// ==UserScript==
// @name       Bypass All Shortlinks
// @namespace  Violentmonkey Scripts
// @run-at     document-start
// @author     Bloggerpemula
// @version        94.0
// @grant          GM_setValue
// @grant          GM_getValue
// @grant          GM_addStyle
// @connect        nocaptchaai.com
// @grant          GM_xmlhttpRequest
// @grant          window.onurlchange
// @grant          GM_registerMenuCommand
// @icon           https://i.ibb.co/qgr0H1n/BASS-Blogger-Pemula.png
// @require        https://update.greasyfork.org/scripts/439099/1203718/MonkeyConfig%20Modern%20Reloaded.js
// @description    Bypass All Shortlinks Sites Automatically Skips Annoying Link Shorteners , Skip AdFly and No Annoying Ads, Directly to Your Destination, and now Support Auto Downloading Your Files
// @match *://*.'gocmod.com'/*
// @match *://*.'api.gplinks.com'/*
// @match *://*.'writedroid.in'/*
// @match *://*.'web1s.com'/*
// @match *://*.'modmania.eu.org'/*
// @match *://*.linkpay.top/*
// @match *://*.'diglies.com'/*
// @match *://*.'vbnmx.online'/*
// @match *://*.'ruwet.us'/*
// @match *://*.'autodime.com'/*
// @match *://*.'fitnesswifi.com'/*
// @match *://*.'marketrook.com'/*
// @match *://*.'ahtio.com'/*
// @match *://*.'switchhindi.com'/*
// @match *://*.'olhonagrana.com'/*
// @match *://*.'veganab.co'/*
// @match *://*.'1apple.xyz'/*
// @match *://*.'akcartoons.in'/*
// @match *://*.'blogsward.com'/*
// @match *://*.'nisnisin.com'/*
// @match *://*.'poco.rcccn.in'/*
// @match *://*.'links.rcccn.in'/*
// @match *://*.'candleoflife.fun'/*
// @match *://*.'suntechu.in'/*
// @match *://*.'market.finclub.in'/*
// @match *://*.'link.sharedp.com'/*
// @match *://*.'poco.devnote.in'/*
// @include /^(https?:\/\/)(.+)?('(mewsr|techstudify).com')(\/.*)/
// @match *://*.'indirasari.com'/*
// @match *://*.'wikitraveltips.com'/*
// @match *://*.'encurtaclik.com'/*
// @match *://*.'appkamods.com'/*
// @match *://*.'keepzem.com'/*
// @match *://*.'venzoars.com'/*
// @match *://*.'short.sharedp.com'/*
// @match *://*.'earn.tensailab.com'/*
// @match *://*.'postazap.com'/*
// @match *://*.'link.devnote.in'/*
// @match *://*.'mamahawa.com'/*
// @match *://*.'shakib.quick91.com'/*
// @match *://*.'reminimod.co'/*
// @match *://*.'indiamaja.com'/*
// @match *://*.'tbhlabsnews.com'/*
// @match *://*.'interestingfactsare.com'/*
// @match *://*.'djnonstopmusic.in'/*
// @match *://*.'travelagancy.com'/*
// @include /^(https?:\/\/)(.+)?('newshuta.in|60fpspubg.one')(\/.*)/
// @match *://*.'tech.filohappy.in'/*
// @match *://*.'kelasadsense.com'/*
// @match *://*.'trust.bgmi32bitapk.in'/*
// @match *://*.'stockinsights.in'/*
// @match *://*.'news.topsarkariyojana.in'/*
// @include /^(https?:\/\/)(.+)?('(cyberlynews|quizrent).com')(\/.*)/
// @match *://*.'cafe.warrenrahul.in'/*
// @match *://*.'earn.bankshiksha.in'/*
// @match *://*.'techurlshort.in'/*
// @match *://*.'ninjamodz.litonmods.com'/*
// @match *://*.'onlinerecruiters.in'/*
// @match *://*.'earnmoneyyt.com'/*
// @match *://*.'kingyojana.com'/*
// @match *://*.'sayphotobooth.com'/*
// @match *://*.'odiadance.com'/*
// @match *://*.'rajdhanimaja.com'/*
// @match *://*.'highkeyfinance.com'/*
// @match *://*.'financeyogi.net'/*
// @match *://*.'finance.marketrook.com'/*
// @include /^(https?:\/\/)(.+)?('(gam3ah|m4cut|soft3arbi|elmokhbir|fatednews|itechmafiia).com')(\/.*)/
// @include /^(https?:\/\/)(.+)?('(surfsees|travelagancy).com')(\/.*)/
// @match *://*.'newkhabar24.com'/*
// @match *://*.mixrootmods.com/*
// @match *://*.go.link4rev.site/*
// @include /^(https?:\/\/)(.+)?('(diglies|indids).com|cryptings.in')(\/.*)/
// @match *://*.infinityskull.com/*
// @match *://*.link.linksfire.co/*
// @match *://*.'ninjamodz.mtcremix.com'/*
// @match *://*.'bharatbestdeals.com'/*
// @include /^(https?:\/\/)(.+)?('earn.thardekho.com|earn.dinoogaming.com')(\/.*)/
// @include /^(https?:\/\/)(.+)?('(examnewstoday|kaomojihub).com')(\/.*)/
// @match *://*.'earnbox.sattakingcharts.in'/*
// @match *://*.'a1.payalgaming.co.in'/*
// @match *://*.dutchycorp.space/*
// @include /^(https?:\/\/)(.+)?('(earnc1.bankshiksha|domain.bgmiupdate.com).in')(\/.*)/
// @include /^(https?:\/\/)(.+)?('(moderngyan|jbstudies|punjabworks).com|(payalgaming.co|star.bgmiupdate.com).in')(\/.*)/
// @include /^(https?:\/\/)(.+)?((teachsansar|technicalatg|foodxor).com)(\/.*)/
// @match *://*.paster.gg/*
// @match *://*.ouo.io/*
// @match *://*.linkbox.to/*
// @match *://*.adbtc.top/*
// @match *://*.upload.ee/*
// @include /^(https?:\/\/)(.+)?(appdrive.*)(\/.*)/
// @match *://*.dayuploads.com/*
// @match *://*.dddrive.me/*
// @match *://*.uppit.com/*
// @match *://*.krakenfiles.com/*
// @match *://*.file-upload.net/*
// @include /^(https?:\/\/)(.+)?(userscloud.com|dosya.co)(\/.*)/
// @match *://*.hexupload.net/*
// @match *://*.gofile.io/*
// @match *://*.rapidgator.net/*
// @match *://*.dbree.me/*
// @match *://*.dropgalaxy.com/*
// @match *://*.megaupto.com/*
// @match *://*.karanpc.com/*
// @match *://*.douploads.net/*
// @match *://*.dataupload.net/*
// @match *://*.buzzheavier.com/*
// @match *://*.filemoon.sx/*
// @match *://*.dailyuploads.net/*
// @match *://*.bestfonts.pro/*
// @match *://*.uploadev.org/*
// @match *://*.files.fm/*
// @match *://*.megaup.net/*
// @match *://*.mega4upload.net/*
// @match *://*.financemonk.net/*
// @include /^(https?:\/\/)(.+)?(usersdrive.com|ddownload.com)(\/.*)/
// @match *://*.adoc.pub/*
// @match *://*.pdfcoffee.com/*
// @match *://*.uploady.io/*
// @match *://*.file-upload.org/*
// @include /^(https?:\/\/)(.+)?(up-load.io|downloadani.me)(\/.*)/
// @match *://*.up-4ever.net/*
// @match *://*.mexa.sh/*
// @match *://*.hitfile.net/*
// @match *://*.4fnet.org/*
// @include /^(https?:\/\/)(.+)?(oxy.*)(\/.*)/
// @match *://*.udrop.com/*
// @match *://*.mp4upload.com/*
// @match *://*.drop.download/*
// @match *://*.workupload.com/*
// @include /^(https?:\/\/)(.+)?(hxfile.co|ex-load.com|megadb.net)(\/.*)/
// @match *://*.send.cm/*
// @match *://*.mega4up.org/*
// @match *://*.uploadhaven.com/*
// @match *://*.k2s.cc/*
// @match *://*.ac.totsugeki.com/*
// @match *://*.anonym.ninja/*
// @match *://*.vosan.co/*
// @match *://*.apkmody.io/*
// @match *://*.mdfx9dc8n.net/*
// @match *://*.takefile.link/*
// @match *://*.appsblaze.com/*
// @match *://*.modcombo.com/*
// @match *://*.1fichier.com/*
// @match *://*.fileresources.net/*
// @match *://*.freepreset.net/*
// @match *://*.doodrive.com/*
// @match *://*.gocmod.com/*
// @include /^(https?:\/\/)(.+)?((uploadrar|fingau|getpczone|wokaz).com|uptomega.me)(\/.*)/
// @match *://*.mediafire.com/*
// @match *://*.qiwi.gg/*
// @match *://*.turbobit.net/*
// @match *://*.sharemods.com/*
// @include /^(https?:\/\/)(.+)?((kusonime|oploverz).org|(opinimedia|beritaotaku|caramasak).com|otakudesu.cc|resepkoki.net|neonime.*)(\/.*)/
// @include /^(https?:\/\/)(.+)?(clickndownload.org|clicknupload.*)(\/.*)/
// @match *://*.leechpub.com/*
// @match *://*.rawlazy.si/*
// @match *://*.downloader.tips/*
// @match *://*.modsbase.com/*
// @include /^(https?:\/\/)(.+)?((thecubexguide|miuiflash).com|(djxmaza|jytechs).in)(\/.*)/
// @match *://*.filedm.com/*
// @match *://*.4shared.com/*
// @match *://*.megaurl.win/*
// @match *://*.keeplinks.org/*
// @match *://*.earnlink.io/*
// @match *://*.mkomsel.com/*
// @match *://*.onimports.com.br/*
// @match *://*.1shortlink.com/*
// @include /^(https?:\/\/)(.+)?(1ink.cc|cuturl.cc)(\/.*)/
// @match *://*.jameeltips.us/*
// @match *://*.post.copydev.com/*
// @match *://*.1short.io/*
// @match *://*.linegee.net/*
// @include /^(https?:\/\/)(.+)?(bedrat.xyz|uhtrdr47.online)(\/.*)/
// @match *://*.pro.sh/*
// @match *://*.playpaste.com/*
// @include /^(https?:\/\/)(.+)?(proappapk.com|meclipstudy.in)(\/.*)/
// @match *://*.1bitspace.com/*
// @match *://*.cshort.org/*
// @match *://*.render-state.to/*
// @include /^(https?:\/\/)(.+)?(offerwall.me|ewall.biz)(\/.*)/
// @match *://*.linkpay.cc/*
// @include /^(https?:\/\/)(.+)?(cooklike.info|model-tas-terbaru.com)(\/.*)/
// @match *://*.kisalt.digital/*
// @include /^(https?:\/\/)(.+)?(bildirim.in|bildirim.eu|bildirim.link)(\/.*)/
// @match *://*.enlacito.com/*
// @match *://*.firefaucet.win/*
// @match *://*.aryx.xyz/*
// @match *://*.webhostingtips.club/*
// @include /^(https?:\/\/)(.+)?(uptobhai.*|uplinkto.*|shortlinkto.*)(\/.*)/
// @include /^(https?:\/\/)(.+)?(michaelemad.com|7misr4day.com)(\/.*)/
// @match *://*.shareus.io/*
// @match *://*.adtival.network/*
// @include /^(https?:\/\/)(.+)?(tii.la|oei.la|iir.la|tvi.la|oii.la|tpi.li)(\/.*)/
// @include /^(https?:\/\/)(.+)?((bnbfree|freeth|freebitco).in)(\/.*)/
// @include /^(https?:\/\/)(.+)?(cutnet.net|(exego|cety).app|(jixo|jizo|gamco).online)(\/.*)/
// @include /^(https?:\/\/)(.+)?(khaddavi.net|contentmenarik.com)(\/.*)/
// @include /^(https?:\/\/)(.+)?(gobits.me|zcash.one|clickscoin.com|beycoin.xyz|bitsusdt.com|adsluffa.online)(\/.*)/
// @match *://*.travelinian.com/*
// @match *://*.sharetext.me/*
// @include /^(https?:\/\/)(.+)?(sfl.gl|moneyblink.com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((fourlinez|newsonnline|phonesparrow|creditcarred).com|(alljntuworld|updatewallah).in)(\/.*)/
// @match *://*.comohoy.com/*
// @match *://*.linkforearn.click/*
// @match *://*.apkw.ru/*
// @include /^(https?:\/\/)(.+)?((newsbawa|utkarshonlinetest).com)(\/.*)/
// @match *://*.programasvirtualespc.net/*
// @include /^(https?:\/\/)(.+)?((blackleadr|shortcuthigh|newztalkies|cybertyrant).com|hubdrive.me|fileroot.net|nzarticles.pro)(\/.*)/
// @include /^(https?:\/\/)(.+)?((10short|lollty).pro|mamahawa.com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((aduzz|tutorialsaya|indobo|baristakesehatan|merekrut).com|deltabtc.xyz|bit4me.info)(\/.*)/
// @include /^(https?:\/\/)(.+)?(cryptfaucet.com|izseo.net)(\/.*)/
// @include /^(https?:\/\/)(.+)?((cryptosparatodos|placementsmela|howtoconcepts|tuasy|skyrimer|foodxor|yodharealty|mobcupring).com|(paidinsurance|sevayojana).in|zaku.pro)(\/.*)/
// @match *://*.fansonlinehub.com/*
// @include /^(https?:\/\/)(.+)?((howifx|vocalley|financerites|yogablogfit|healthfirstweb|junkyponk|mythvista|blog-myst).com|ss7.info|sololevelingmanga.pics)(\/.*)/
// @include /^(https?:\/\/)(.+)?((viralxns|uploadsoon).com)(\/.*)/
// @match *://*.setroom.biz.id/*
// @include /^(https?:\/\/)(.+)?(ouo.io|ouo.press)(\/.*)/
// @include /^(https?:\/\/)(.+)?(largestpanel.in|earnme.club|usanewstoday.club)(\/.*)/
// @match *://*.lksfy.com/*
// @include /^(https?:\/\/)(.+)?(paste1s.com|note1s.com)(\/.*)/
// @match *://*.terabox.fun/*
// @match *://*.karyawan.co.id/*
// @match *://*.icerik.site/*
// @match *://*.ponselharian.com/*
// @match *://*.assettoworld.com/*
// @match *://*.adfoc.us/*
// @include /^(https?:\/\/)(.+)?(yoshare.net|olhonagrana.com)(\/.*)/
// @match *://*.oii.io/*
// @include /^(https?:\/\/)(.+)?(mrproblogger.com|themezon.net)(\/.*)/
// @include /^(https?:\/\/)(.+)?(forex-golds.com|forex-trnd.com)(\/.*)/
// @match *://*.1link.club/*
// @match *://*.slink.bid/*
// @match *://*.blog.yurasu.xyz/*
// @match *://*.zegtrends.com/*
// @include /^(https?:\/\/)(.+)?(coincroco.com|surflink.tech)(\/.*)/
// @include /^(https?:\/\/)(.+)?(solidcoins.net|fishingbreeze.com)(\/.*)/
// @match *://*.bigbtc.win/*
// @match *://*.linkspy.cc/*
// @include /^(https?:\/\/)(.+)?((superheromaniac|spatsify|mastkhabre|ukrupdate).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?(4hi.in|shortie.sbs|10short.com|finish.wlink.us)(\/.*)/
// @match *://*.chainfo.xyz/*
// @match *://*.100puan.com/*
// @match *://*.sub2get.com/*
// @include /^(https?:\/\/)(.+)?((fc-lc|loaninsurehub).com|fc-lc.xyz)(\/.*)/
// @match *://*.go.shareus.in/*
// @include /^(https?:\/\/)(.+)?(infonerd.org|coingraph.us)(\/.*)/
// @match *://*.leitup.com/*
// @include /^(https?:\/\/)(.+)?((blogmado|kredilerim|insuranceleadsinfo).com)(\/.*)/
// @match *://*.azmath.info/*
// @match *://*.coinsrev.com/*
// @match *://*.newassets.hcaptcha.com/*
// @include /^(https?:\/\/)(.+)?((ez4mods|tensailab|game5s|supermodsmenus).com|tech5s.co)(\/.*)/
// @match *://*.mazen-ve3.com/*
// @match *://*.soft3arbi.com/*
// @include /^(https?:\/\/)(.+)?((coinsward|blogsward).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((tmail|labgame).io|(gamezizo|fitdynamos).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((exeo|exego).app|(falpus|exe-urls).com|4ace.online)(\/.*)/
// @include /^(https?:\/\/)(.+)?((forexrw7|forex-articles|3rabsports|fx-22|watchtheeye).com|gold-24.net|(offeergames|todogame).online)(\/.*)/
// @match *://*.o-pro.online/*
// @include /^(https?:\/\/)(.+)?(nishankhatri.xyz|(bebkub|importantclass|owoanime|hyperkhabar).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((kongutoday|proappapk|hipsonyc|teamtechnews).com|yotrickslog.tech)(\/.*)/
// @include /^(https?:\/\/)(.+)?(writedroid.eu.org|modmania.eu.org|writedroid.in)(\/.*)/
// @include /^(https?:\/\/)(.+)?((travelironguide|businesssoftwarehere|softwaresolutionshere|freevpshere).com)(\/.*)/
// @match *://*.linkatla.com/*
// @match *://*.claimfreetrx.online/*
// @include /^(https?:\/\/)(.+)?(adclicker.*|yourihollier.com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((mgame|sportweb|bitcrypto).info)(\/.*)/
// @match *://*.easylink.gamingwithtr.com/*
// @include /^(https?:\/\/)(.+)?((horoscop|videoclip).info|article24.online|writeprofit.org|docadvice.eu|trendzilla.club)(\/.*)/
// @include /^(https?:\/\/)(.+)?('(on-scroll|diudemy|maqal360).com')(\/.*)/
// @match *://*.onlinetechsolution.link/*
// @include /^(https?:\/\/)(.+)?(coinhub.wiki|(vitalityvista|geekgrove).net)(\/.*)/
// @include /^(https?:\/\/)(.+)?(stly.link|snaplessons.net|atravan.net|stfly.biz|airevue.net)(\/.*)/
// @include /^(https?:\/\/)(.+)?((mangareleasedate|freemodapp|zutiza|phixshop|uskloans|sabkiyojana|dulimo|merikahaniya|kloota|nspaconline|etrovo).com|(myfirstname|ignoupur).in|sarkarisahayata.org|kisannews.net|bloxstrap.cc|90fpsbgmi.one)(\/.*)/
// @include /^(https?:\/\/)(.+)?((remixsounds|helpdeep|thinksrace).com|uprwssp.org)(\/.*)/
// @include /^(https?:\/\/)(.+)?(shrinke.*|shrinkme.*|(paid4link|linkbulks|linclik|up4cash|smoner|atglinks).com|(wordcounter|shrink).icu|(dutchycorp|galaxy-link).space|dutchycorp.ovh|pahe.plus|(pwrpa|snipn).cc|paylinks.cloud|oke.io|tinygo.co|tlin.me)(\/.*)/
// @include /^(https?:\/\/)(.+)?(revly.click|mitly.us)(\/.*)/
// @include /^(https?:\/\/)(.+)?(trangchu.news|downfile.site|(techacode|expertvn|ziggame).com|azmath.info|aztravels.net|top10cafe.se|handydecor.com.vn)(\/.*)/
// @include /^(https?:\/\/)(.+)?((askpaccosi|wellness4live|akash.classicoder).com|2the.space|inicerita.online|cryptomonitor.in)(\/.*)/
// @include /^(https?:\/\/)(.+)?((hosttbuzz|policiesreview|blogmystt|wp2hostt|advertisingcamps).com|clk.kim|dekhe.click)(\/.*)/
// @include /^(https?:\/\/)(.+)?(techyreviewx.com|desiupload.co)(\/.*)/
// @include /^(https?:\/\/)(.+)?((blogsward|coinjest).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?(exactpay.online|neverdims.com|sproutworkers.co|coinsfaucet.fun)(\/.*)/
// @include /^(https?:\/\/)(.+)?((btcpany|zombiebtc|claimfey|thefastpost).com|(panytourism|statepany).online)(\/.*)/
// @match *://*.playnano.online/*
// @match *://*.rekonise.com/*
// @match *://*.acortalink.me/*
// @include /^(https?:\/\/)(.+)?(tutwuri.id|(besargaji|link2unlock).com)(\/.*)/
// @match *://*.autodime.com/*
// @match *://*.amritadrino.com/*
// @include /^(https?:\/\/)(.+)?(hunterkiller.me|surflink.tech)(\/.*)/
// @include /^(https?:\/\/)(.+)?((lyricsbaazaar|ezeviral).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((sekilastekno|miuiku|vebma|majalahhewan).com|tempatwisata.pro)(\/.*)/
// @match *://*.socialwolvez.com/*
// @include /^(https?:\/\/)(.+)?((mobi2c|healthy4pepole|healdad|world2our|mobitaak|te-it|businessnews-nigeria|govaf|fahmysport).com|(hightrip|fx-gd|world-trips|otechno|bluetechno|to-travel).net|(newforex|forexit).online)(\/.*)/
// @match *://*.bitcotasks.com/*
// @match *://*.suaurl.com/*
// @match *://*.letsboost.net/*
// @include /^(https?:\/\/)(.+)?(oncoin.info|nishankhatri.com.np|quanngon.org)(\/.*)/
// @include /^(https?:\/\/)(.+)?((lootlinks|onepiecered).co|(loot-links|links-loot|loot-link|mega-guy|utopianleaks|eofmukindwo|realiukzemydre|kmendation|bstlar|tonordersitye|bleleadersto|daughablelea).com|(lootdest|lootlink|best-links).org|lootdest.info|linksloot.net|free-content.pro)(\/.*)/
// @include /^(https?:\/\/)(.+)?('(cryptowidgets|gadgetbuzz|coinsvalue|coinstrend|coinsrise|webfreetools|wanderjourney|languagefluency|giftmagic).net|(freeoseocheck|insurancexguide|funplayarcade|origamiarthub|fitbodygenius|illustrationmaster|selfcareinsights|ecofriendlyz|virtualrealitieshub|brewmasterly).com|coinscap.info|bubblix.eu')(\/.*)/
// @include /^(https?:\/\/)(.+)?(playonpc.online|quins.us|(retrotechreborn|insurelean|ecosolardigest).com|gally.shop)(\/.*)/
// @match *://*.shortit.pw/*
// @include /^(https?:\/\/)(.+)?(short.croclix.me|adz7short.space)(\/.*)/
// @include /^(https?:\/\/)(.+)?(adshnk.com|adshrink.it)(\/.*)/
// @match *://*.ify.ac/*
// @match *://*.lanza.me/*
// @match *://*.lifeezee.com/*
// @match *://*.lolinez.com/*
// @match *://*.file-upload.in/*
// @match *://*.linksly.co/*
// @match *://*.appsinsta.com/*
// @match *://*.apkadmin.com/*
// @match *://*.sugarona.com/*
// @match *://*.cekip.site/*
// @include /^(https?:\/\/)(.+)?(techleets.xyz|sharphindi.in)(\/.*)/
// @match *://*.amanguides.com/*
// @match *://*.8tm.net/*
// @match *://*.cpmlink.net/*
// @match *://*.noodlemagazine.com/*
// @match *://*.paycut.pro/*
// @match *://*.mohtawaa.com/*
// @match *://*.rockmods.net/*
// @include /^(https?:\/\/)(.+)?(xonnews.net|toilaquantri.com|share4u.men|camnangvay.com)(\/.*)/
// @match *://*.boost.ink/*
// @match *://*.blog.textpage.xyz/*
// @match *://*.foodupe.com/*
// @include /^(https?:\/\/)(.+)?((cricketgurupro|travelkuku).com)(\/.*)/
// @match *://*.mirrored.to/*
// @match *://*.sub2unlock.net/*
// @include /^(https?:\/\/)(.+)?((financenube|mixrootmods|pastescript|trimorspacks|mealcold).com)(\/.*)/
// @match *://*.mboost.me/*
// @include /^(https?:\/\/)(.+)?((disheye|kreatifparenting|phimne|admediaflex|cdrab).com|(gurumu|wpcheap|izseo|adcrypto|daycash).net|(ecq|oncoin).info|savego.org|hbz.us|(djqunjab|alpha-links).in|datacheap.io)(\/.*)/
// @include /^(https?:\/\/)(.+)?(mbantul.my.id|crypto-fi.net|claimcrypto.cc|xtrabits.click|(cempakajaya|web9academy|onlineincoms|allsoftdrivers|tribuncrypto|poketoonworld|bioinflu|pubgquotes|bico8).com|(techleets|ourcoincash|studyis|healthysamy).xyz)(\/.*)/
// @include /^(https?:\/\/)(.+)?(dutchycorp.ovh|seulink.digital|oii.io|hamody.pro|metasafelink.site|(beingtek|fc-lc|10short).com|(zagl|shrinkforearn).in|wordcounter.icu|pwrpa.cc|flyad.vip|seulink.online|pahe.plus|tfly.link)(\/.*)/
// @match *://*.autofaucet.dutchycorp.space/*
// @match *://*.gocmod.com/*
// @match *://*.api.gplinks.com/*
// @match *://*.writedroid.in/*
// @match *://*.web1s.com/*
// @match *://*.modmania.eu.org/*
// @match *://*.diglies.com/*
// @match *://*.vbnmx.online/*
// @match *://*.ruwet.us/*
// @match *://*.autodime.com/*
// @match *://*.fitnesswifi.com/*
// @match *://*.marketrook.com/*
// @match *://*.ahtio.com/*
// @match *://*.switchhindi.com/*
// @match *://*.olhonagrana.com/*
// @match *://*.veganab.co/*
// @match *://*.1apple.xyz/*
// @match *://*.akcartoons.in/*
// @match *://*.blogsward.com/*
// @match *://*.nisnisin.com/*
// @match *://*.poco.rcccn.in/*
// @match *://*.links.rcccn.in/*
// @match *://*.candleoflife.fun/*
// @match *://*.suntechu.in/*
// @match *://*.market.finclub.in/*
// @match *://*.link.sharedp.com/*
// @match *://*.poco.devnote.in/*
// @include /^(https?:\/\/)(.+)?((mewsr|techstudify).com)(\/.*)/
// @match *://*.indirasari.com/*
// @match *://*.wikitraveltips.com/*
// @match *://*.encurtaclik.com/*
// @match *://*.appkamods.com/*
// @match *://*.keepzem.com/*
// @match *://*.venzoars.com/*
// @match *://*.short.sharedp.com/*
// @match *://*.earn.tensailab.com/*
// @match *://*.postazap.com/*
// @match *://*.link.devnote.in/*
// @match *://*.mamahawa.com/*
// @match *://*.shakib.quick91.com/*
// @match *://*.reminimod.co/*
// @match *://*.indiamaja.com/*
// @match *://*.tbhlabsnews.com/*
// @match *://*.interestingfactsare.com/*
// @match *://*.djnonstopmusic.in/*
// @match *://*.travelagancy.com/*
// @include /^(https?:\/\/)(.+)?(newshuta.in|60fpspubg.one)(\/.*)/
// @match *://*.tech.filohappy.in/*
// @match *://*.kelasadsense.com/*
// @match *://*.trust.bgmi32bitapk.in/*
// @match *://*.stockinsights.in/*
// @match *://*.news.topsarkariyojana.in/*
// @include /^(https?:\/\/)(.+)?((cyberlynews|quizrent).com)(\/.*)/
// @match *://*.cafe.warrenrahul.in/*
// @match *://*.earn.bankshiksha.in/*
// @match *://*.techurlshort.in/*
// @match *://*.ninjamodz.litonmods.com/*
// @match *://*.onlinerecruiters.in/*
// @match *://*.earnmoneyyt.com/*
// @match *://*.kingyojana.com/*
// @match *://*.sayphotobooth.com/*
// @match *://*.odiadance.com/*
// @match *://*.rajdhanimaja.com/*
// @match *://*.highkeyfinance.com/*
// @match *://*.financeyogi.net/*
// @match *://*.finance.marketrook.com/*
// @include /^(https?:\/\/)(.+)?((gam3ah|m4cut|soft3arbi|elmokhbir|fatednews|itechmafiia).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((surfsees|travelagancy).com)(\/.*)/
// @match *://*.newkhabar24.com/*
// @include /^(https?:\/\/)(.+)?((diglies|indids).com|cryptings.in)(\/.*)/
// @match *://*.ninjamodz.mtcremix.com/*
// @match *://*.bharatbestdeals.com/*
// @include /^(https?:\/\/)(.+)?(earn.thardekho.com|earn.dinoogaming.com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((examnewstoday|kaomojihub).com)(\/.*)/
// @match *://*.earnbox.sattakingcharts.in/*
// @match *://*.a1.payalgaming.co.in/*
// @include /^(https?:\/\/)(.+)?((earnc1.bankshiksha|domain.bgmiupdate.com).in)(\/.*)/
// @include /^(https?:\/\/)(.+)?((moderngyan|jbstudies|punjabworks).com|(payalgaming.co|star.bgmiupdate.com).in)(\/.*)/
// @include /^(https?:\/\/)(.+)?((on-scroll|diudemy|maqal360).com)(\/.*)/
// @include /^(https?:\/\/)(.+)?((cryptowidgets|gadgetbuzz|coinsvalue|coinstrend|coinsrise|webfreetools|wanderjourney|languagefluency|giftmagic).net|(freeoseocheck|insurancexguide|funplayarcade|origamiarthub|fitbodygenius|illustrationmaster|selfcareinsights|ecofriendlyz|virtualrealitieshub|brewmasterly).com|coinscap.info|bubblix.eu)(\/.*)/
// @match *://*.multiup.org/*
// @match *://*.modsfire.com/*
// @match *://*.pixeldrain.com/*
// @match *://*.social-unlock.com/*
// @match *://*.work.ink/*
// @match *://*.uii.io/*
// @match *://*.shortano.link/*
// @match *://*.shortino.link/*
// @match *://*.clk.st/*
// @match *://*.clks.pro/*
// @match *://*.chainfo.xyz/*
// @match *://*.clicksfly.com/*
// @match *://*.tryshort.in/*
// @match *://*.dailytime.store/*
// @match *://*.ez4short.com/*
// @match *://*.fc.lc/*
// @match *://*.cutp.in/*
// @match *://*.saly.io/*
// @match *://*.earnow.online/*
// @match *://*.gplinks.in/*
// @match *://*.linkfly.me/*
// @match *://*.linksfire.co/*
// @match *://*.adlink.click/*
// @match *://*.linkjust.com/*
// @match *://*.linkbulks.com/*
// @match *://*.traffic1s.com/*
// @match *://*.link4rev.site/*
// @match *://*.linkrex.net/*
// @match *://*.opli.xyz/*
// @match *://*.linksly.co/*
// @match *://*.ninjaurl.net/*
// @match *://*.shortyearn.com/*
// @match *://*.upshrink.com/*
// @match *://*.tr.link/*
// @match *://*.megaurl.in/*
// @match *://*.adshort.co/*
// @match *://*.atglinks.com/*
// @match *://*.shrinkforearn.in/*
// @match *://*.shorti.io/*
// @match *://*.try2link.com/*
// @match *://*.terafly.me/*
// @match *://*.www.wts.pw/*
// @match *://*.clk.sh/*
// @match *://*.web1s.com/*
// @match *://*.rocklinks.net/*
// @match *://*.megafly.in/*
// @match *://*.usalink.io/*
// @match *://*.adrinolinks.in/*
// @match *://*.10short.com/*
// @match *://*.urlpay.in/*
// @match *://*.mdiskshortner.link/*
// @match *://*.cbshort.com/*
// @match *://*.droplink.co/*
// @match *://*.paid4link.com/*
// @match *://*.cuty.io/*
// @match *://*.doshrink.com/*
// @match *://*.revly.click/*
// @match *://*.shrinkearn.com/*
// @match *://*.shrinkme.io/*
// @match *://*.shortox.com/*
// @match *://*.linksfly.link/*
// @match *://*.oii.io/*
// @match *://*.ay.live/*
// @match *://*.urlstox.com/*
// @match *://*.gamerfang.in/*
// @match *://*.blog.mphealth.online/*
// @match *://*.mphealth.online/*
// @match *://*.shrs.link/*
// @match *://*.shareus.io/*
// @match *://*.www.gifans.com/*
// @match *://*.www.pythondunyasi.com/*
// @match *://*.sl1bas.blogspot.com/*
// @match *://*.jrlinks.in/*
// @match *://*.hr.vikashmewada.com/*
// @match *://*.freeltc.top/*
// @match *://*.freecrypto.top/*
// @match *://*.insfly.pw/*
// @match *://*.Insfly.pw/*
// @match *://*.mdiskshortner.link/*
// @match *://*.clockads.in/*
// @match *://*.exashorts.fun/*
// @match *://*.videolyrics.in/*
// @match *://*.terafly.me/*
// @match *://*.adnews.me/*
// @match *://*.kyshort.xyz/*
// @match *://*.eazyurl.xyz/*
// @exclude /^(https?:\/\/)([^\/]+\.)?((github|aliyun|reddit|bing|yahoo|microsoft|whatsapp|amazon|ebay|payoneer|paypal|skrill|stripe|tipalti|wise|discord|tokopedia|taobao|taboola|aliexpress|netflix|citigroup|spotify|bankofamerica|hsbc|blogger|accounts.youtube|(cloud|mail|translate|analytics|accounts|myaccount|contacts|clients6|developers|payments|pay|ogs|safety|wallet).google|atlassian|pinterest|twitter|x|live|facebook|tiktok|instagram|linkedin|fastbull|tradingview|deepseek|chatgpt|openai|playghub|bilibili).com|proton.me|(greasyfork|openuserjs|telegram|wikipedia|lichess).org|doubleclick.net|adoptimum.top|codepen.io|(shopee|lazada|rakuten|maybank|binance).*|(dana|ovo|bca.co|bri.co|bni.co|bankmandiri.co|desa|(.*).go).id|(.*).(edu|gov))(\/.*)/
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Shortlink/release/release/2.user.js
// @updateURL  https://raw.githubusercontent.com/FiorenMas/Shortlink/release/release/2.meta.js
// ==/UserScript==
