name: Edit
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  patch1:
    name: Edit
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Edit
        run: |
          npm install async
          mkdir ./release
          chmod +x Edit.js
          ./Edit.js
        env:
          repository: ${{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ./release/*
          name: Userscript
          tag_name: all
          body: Download Here
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v1
