name: Edit
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  edit:
    name: Edit
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Edit
        run: |
          npm install async
          mkdir ./release
          chmod +x editor.js include.js
          ./editor.js
          cp ./release/ShortLink1-modified.user.js ./release/ShortLink1-modified-include.user.js
          ./include.js
      - name: Convert
        run: bash convert.sh
        env:
          repository: ${{ github.repository }}
      - name: Release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release
          skip_checkout: true
          skip_dirty_check: true
          push_options: '--force'
          file_pattern: ./release/*
          commit_message: Bump
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
