name: Fix
on:
  workflow_dispatch:
jobs:
  Fix_Readme:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Fix
        run: |
            curl -o README.md https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
            curl -o editor.js https://raw.githubusercontent.com/${{ github.repository }}/main/editor.js
            sed -i "s#FiorenMas/Shortlink#${{ github.repository }}#g" README.md
            sed -i "s#FiorenMas/Shortlink#${{ github.repository }}#g" editor.js
      - name: Commit Readme
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'README.md'
          default_author: github_actor
          message: 'Edit Readme'
          push: true
      - name: Commit Readme
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'editor.js'
          default_author: github_actor
          message: 'Edit Readme'
          push: true
